version: '3'

services:
  schema_extensions:
    build:
      context: .
    container_name: idchain-schema
    image: idchain/schema-extensions
    environment:
      - IDC_SCHEMA_IP=${IDC_SCHEMA_IP-0.0.0.0}
      - IDC_SCHEMA_PORT=${IDC_SCHEMA_PORT-9000}
