version: '3'

networks:
  indy-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "${IDC_POOL_SUBNET}"

services:
  pool:
    image: idchain/test-pool:1.4
    ports:
    - ${IDC_POOL_PORTS:-9701-9708}:${IDC_POOL_PORTS:-9701-9708}
    - ${IDC_POOL_INFO_PORT-8001}:${IDC_POOL_INFO_PORT-8001}
    environment:
    - IDC_POOL_IP
    - IDC_POOL_NAME=${IDC_POOL_NAME:-sandbox}
    - IDC_PORT_START=${IDC_PORT_START:-9700}
    networks:
      indy-network:
        ipv4_address: "${IDC_POOL_IP}"


 

